### ISSUE TITLE
Doble ejecución de pruebas en TravisCI

### ISSUE THREAD

**Issue by antsuabon** [ispp-yourney/yourney-backend#23]
Cuando se ejecutan las pruebas de TravisCI se puede observar que se han obtenido los resultados de la ejecución de las pruebas dos veces.

Este suceso es observable en la siguente build de Travis: [Build 18 de TravisCI](https://travis-ci.org/github/ispp-yourney/yourney-backend/builds/763335390)

**Comment by edubotdom** [comment]
Se ha procedido a modificar el fichero .Travis.yml, que ejecutaba el comando `mvn test` en dos ocasiones, una por parte de Maven y otra de SonarCloud para transferir parámetros de calidad del código.
