### ISSUE TITLE
Refactorización del modelo

### ISSUE THREAD

**Issue by edubotdom** [ispp-yourney/yourney-backend#47]
DESCRIPCIÓN: En esta tarea pretendemos acometer una simplificación del modelo, al nivel de querer eliminar entidades y propiedades diseñadas inicialmente.

FECHA RELATIVA: 24-03 - 29-03

**Comment by antsuabon** [comment]
Por hacer:
- Queda comprobar el correcto fucionamiento de la aplicación.
- Eliminar código comendo.
- Aumentar la calidad del código.
